"""empty message

Revision ID: 7c65537e75da
Revises: 9bd3bc7574b2
Create Date: 2020-03-08 11:28:55.509668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c65537e75da'
down_revision = '9bd3bc7574b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('releaseDate', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('age', sa.String(length=1000), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('eyeColor', sa.String(length=1000), nullable=True),
    sa.Column('hairColor', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('char_length(name) > 0', name='name column is required'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_cast',
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_cast')
    op.drop_table('person')
    op.drop_table('movie')
    # ### end Alembic commands ###
